### ISSUE TITLE
In version 0.5.0. Execute nlsrc lsdb, the LSDB info can dump out, but also report double free error

### ISSUE THREAD

**Issue by SunnyQjm** [named-data/NLSR#11]
*** Error in `nlsrc': double free or corruption (!prev): 0x0000000001545c80 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f3575bdd7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f3575be637a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f3575bea53c]
nlsrc(_ZN3ndn4NameD1Ev+0x3b)[0x42c15b]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x9a)[0x7f3575ba036a]
/usr/local/lib/libndn-cxx.so.0.6.3(+0x15e593)[0x7f3574915593]
======= Memory map: ========
00400000-0053d000 r-xp 00000000 08:01 13371563                           /usr/local/bin/nlsrc
0053e000-0053f000 r--p 0013d000 08:01 13371563                           /usr/local/bin/nlsrc
0053f000-00540000 rw-p 0013e000 08:01 13371563                           /usr/local/bin/nlsrc
00540000-00546000 rw-p 00000000 00:00 0 
0152f000-015bb000 rw-p 00000000 00:00 0                                  [heap]
7f356c000000-7f356c021000 rw-p 00000000 00:00 0 
7f356c021000-7f3570000000 ---p 00000000 00:00 0 
7f3573988000-7f3573989000 ---p 00000000 00:00 0 
7f3573989000-7f3574189000 rw-p 00000000 00:00 0 
7f3574189000-7f35741a2000 r-xp 00000000 08:01 8655495                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f35741a2000-7f35743a1000 ---p 00019000 08:01 8655495                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f35743a1000-7f35743a2000 r--p 00018000 08:01 8655495                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f35743a2000-7f35743a3000 rw-p 00019000 08:01 8655495                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f35743a3000-7f35743b2000 r-xp 00000000 08:01 8655303                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f35743b2000-7f35745b1000 ---p 0000f000 08:01 8655303                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f35745b1000-7f35745b2000 r--p 0000e000 08:01 8655303                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f35745b2000-7f35745b3000 rw-p 0000f000 08:01 8655303                    /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f35745b3000-7f35745b6000 r-xp 00000000 08:01 8657707                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f35745b6000-7f35747b5000 ---p 00003000 08:01 8657707                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f35747b5000-7f35747b6000 r--p 00002000 08:01 8657707                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f35747b6000-7f35747b7000 rw-p 00003000 08:01 8657707                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f35747b7000-7f3574bde000 r-xp 00000000 08:01 13508167                   /usr/local/lib/libndn-cxx.so.0.6.3
7f3574bde000-7f3574bf0000 r--p 00426000 08:01 13508167                   /usr/local/lib/libndn-cxx.so.0.6.3
7f3574bf0000-7f3574bfa000 rw-p 00438000 08:01 13508167                   /usr/local/lib/libndn-cxx.so.0.6.3
7f3574bfa000-7f3574bfe000 rw-p 00000000 00:00 0 
7f3574bfe000-7f3574c15000 r-xp 00000000 08:01 13377513                   /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f3574c15000-7f3574e15000 ---p 00017000 08:01 13377513                   /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f3574e15000-7f3574e16000 r--p 00017000 08:01 13377513                   /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f3574e16000-7f3574e17000 rw-p 00018000 08:01 13377513                   /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
7f3574e17000-7f3574e1e000 r-xp 00000000 08:01 8657705                    /lib/x86_64-linux-gnu/librt-2.23.so
7f3574e1e000-7f357501d000 ---p 00007000 08:01 8657705                    /lib/x86_64-linux-gnu/librt-2.23.so
7f357501d000-7f357501e000 r--p 00006000 08:01 8657705                    /lib/x86_64-linux-gnu/librt-2.23.so
7f357501e000-7f357501f000 rw-p 00007000 08:01 8657705                    /lib/x86_64-linux-gnu/librt-2.23.so
7f357501f000-7f35750ee000 r-xp 00000000 08:01 13374248                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f35750ee000-7f35752ed000 ---p 000cf000 08:01 13374248                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f35752ed000-7f35752f0000 r--p 000ce000 08:01 13374248                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f35752f0000-7f35752f2000 rw-p 000d1000 08:01 13374248                   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f35752f2000-7f35752f3000 rw-p 00000000 00:00 0 
7f35752f3000-7f357550e000 r-xp 00000000 08:01 8655206                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f357550e000-7f357570d000 ---p 0021b000 08:01 8655206                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f357570d000-7f3575729000 r--p 0021a000 08:01 8655206                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f3575729000-7f3575735000 rw-p 00236000 08:01 8655206                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f3575735000-7f3575738000 rw-p 00000000 00:00 0 
7f3575738000-7f357575c000 r-xp 00000000 08:01 13380702                   /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f357575c000-7f357595b000 ---p 00024000 08:01 13380702                   /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f357595b000-7f357595d000 r--p 00023000 08:01 13380702                   /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f357595d000-7f357595e000 rw-p 00025000 08:01 13380702                   /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
7f357595e000-7f3575964000 r-xp 00000000 08:01 13380699                   /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f3575964000-7f3575b64000 ---p 00006000 08:01 13380699                   /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f3575b64000-7f3575b65000 r--p 00006000 08:01 13380699                   /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f3575b65000-7f3575b66000 rw-p 00007000 08:01 13380699                   /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0
7f3575b66000-7f3575d26000 r-xp 00000000 08:01 8657722                    /lib/x86_64-linux-gnu/libc-2.23.so
7f3575d26000-7f3575f26000 ---p 001c0000 08:01 8657722                    /lib/x86_64-linux-gnu/libc-2.23.so
7f3575f26000-7f3575f2a000 r--p 001c0000 08:01 8657722                    /lib/x86_64-linux-gnu/libc-2.23.so
7f3575f2a000-7f3575f2c000 rw-p 001c4000 08:01 8657722                    /lib/x86_64-linux-gnu/libc-2.23.so
7f3575f2c000-7f3575f30000 rw-p 00000000 00:00 0 
7f3575f30000-7f3575f46000 r-xp 00000000 08:01 8655342                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3575f46000-7f3576145000 ---p 00016000 08:01 8655342                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3576145000-7f3576146000 rw-p 00015000 08:01 8655342                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3576146000-7f357624e000 r-xp 00000000 08:01 8657725                    /lib/x86_64-linux-gnu/libm-2.23.so
7f357624e000-7f357644d000 ---p 00108000 08:01 8657725                    /lib/x86_64-linux-gnu/libm-2.23.so
7f357644d000-7f357644e000 r--p 00107000 08:01 8657725                    /lib/x86_64-linux-gnu/libm-2.23.so
7f357644e000-7f357644f000 rw-p 00108000 08:01 8657725                    /lib/x86_64-linux-gnu/libm-2.23.so
7f357644f000-7f35765c1000 r-xp 00000000 08:01 13371525                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f35765c1000-7f35767c1000 ---p 00172000 08:01 13371525                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f35767c1000-7f35767cb000 r--p 00172000 08:01 13371525                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f35767cb000-7f35767cd000 rw-p 0017c000 08:01 13371525                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f35767cd000-7f35767d1000 rw-p 00000000 00:00 0 
7f35767d1000-7f35767e9000 r-xp 00000000 08:01 8657709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f35767e9000-7f35769e8000 ---p 00018000 08:01 8657709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f35769e8000-7f35769e9000 r--p 00017000 08:01 8657709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f35769e9000-7f35769ea000 rw-p 00018000 08:01 8657709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f35769ea000-7f35769ee000 rw-p 00000000 00:00 0 
7f35769ee000-7f3576ac0000 r-xp 00000000 08:01 13380796                   /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
7f3576ac0000-7f3576cc0000 ---p 000d2000 08:01 13380796                   /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
7f3576cc0000-7f3576cc6000 r--p 000d2000 08:01 13380796                   /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
7f3576cc6000-7f3576cc7000 rw-p 000d8000 08:01 13380796                   /usr/lib/x86_64-linux-gnu/libboost_log.so.1.58.0
7f3576cc7000-7f3576cde000 r-xp 00000000 08:01 13377512                   /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f3576cde000-7f3576edd000 ---p 00017000 08:01 13377512                   /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f3576edd000-7f3576ede000 r--p 00016000 08:01 13377512                   /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f3576ede000-7f3576edf000 rw-p 00017000 08:01 13377512                   /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7f3576edf000-7f3576ee2000 r-xp 00000000 08:01 13377514                   /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
7f3576ee2000-7f35770e1000 ---p 00003000 08:01 13377514                   /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
7f35770e1000-7f35770e2000 r--p 00002000 08:01 13377514                   /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
7f35770e2000-7f35770e3000 rw-p 00003000 08:01 13377514                   /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
7f35770e3000-7f3577511000 r-xp 00000000 08:01 13505851                   /usr/local/lib/libndn-cxx.so.0.6.5
7f3577511000-7f3577512000 ---p 0042e000 08:01 13505851                   /usr/local/lib/libndn-cxx.so.0.6.5
7f3577512000-7f3577524000 r--p 0042e000 08:01 13505851                   /usr/local/lib/libndn-cxx.so.0.6.5
7f3577524000-7f357752e000 rw-p 00440000 08:01 13505851                   /usr/local/lib/libndn-cxx.so.0.6.5
7f357752e000-7f3577531000 rw-p 00000000 00:00 0 
7f3577531000-7f3577557000 r-xp 00000000 08:01 8657708                    /lib/x86_64-linux-gnu/ld-2.23.so
7f3577632000-7f3577645000 rw-p 00000000 00:00 0 
7f3577645000-7f35776b9000 r-xp 00000000 08:01 13505894                   /usr/local/lib/libPSync.so
7f35776b9000-7f35776ba000 ---p 00074000 08:01 13505894                   /usr/local/lib/libPSync.so
7f35776ba000-7f35776bc000 r--p 00074000 08:01 13505894                   /usr/local/lib/libPSync.so
7f35776bc000-7f35776be000 rw-p 00076000 08:01 13505894                   /usr/local/lib/libPSync.so
7f35776be000-7f35776bf000 rw-p 00000000 00:00 0 
7f35776bf000-7f3577735000 r-xp 00000000 08:01 13508214                   /usr/local/lib/libChronoSync.so.0.5.2
7f3577735000-7f3577736000 ---p 00076000 08:01 13508214                   /usr/local/lib/libChronoSync.so.0.5.2
7f3577736000-7f3577739000 r--p 00076000 08:01 13508214                   /usr/local/lib/libChronoSync.so.0.5.2
7f3577739000-7f357773b000 rw-p 00079000 08:01 13508214                   /usr/local/lib/libChronoSync.so.0.5.2
7f357773b000-7f357773d000 rw-p 00000000 00:00 0 
7f3577755000-7f3577756000 rw-p 00000000 00:00 0 
7f3577756000-7f3577757000 r--p 00025000 08:01 8657708                    /lib/x86_64-linux-gnu/ld-2.23.so
7f3577757000-7f3577758000 rw-p 00026000 08:01 8657708                    /lib/x86_64-linux-gnu/ld-2.23.so
7f3577758000-7f3577759000 rw-p 00000000 00:00 0 
7ffc0651e000-7ffc0653f000 rw-p 00000000 00:00 0                          [stack]
7ffc0656c000-7ffc0656f000 r--p 00000000 00:00 0                          [vvar]
7ffc0656f000-7ffc06571000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by agawande** [comment]
ndn-cxx is old version (0.6.3). Please use the latest 0.6.5.

**Comment by SunnyQjm** [comment]
Get it, thanks~

> ndn-cxx is old version (0.6.3). Please use the latest 0.6.5.
