### ISSUE TITLE
./waf fails

### ISSUE THREAD

**Issue by nikosft** [named-data/NLSR#12]
./waf fails with the following error

```
src/nlsr.cpp:34:10: fatal error: ndn-cxx/signature.hpp: No such file or directory
```

It should be noted that ndn-cxx/signature.hpp has been removed from ndn-cxx with the commit  a86300a8671aaac35e035328563ddf31215acfb 

A temporary workaround I used was to checkout version 0b2aa13fbf2cc72e6c1f3dee4802cf726d9907a6 of ndn-cxx

**Comment by dulalsaurab** [comment]
This issue has been resolved by the recent commits.
