### ISSUE TITLE
nlsr: symbol lookup error

### ISSUE THREAD

**Issue by kangkang333** [named-data/NLSR#16]
in /usr/bin directory, run nlsr command , there is an error: 

nlsr: symbol lookup error: nlsr: undefined symbol: _ZN3ndn8security2v211Certificate17DEFAULT_ISSUER_IDE

**Comment by kangkang333** [comment]
thanks, ask a further question, Does NLSR require a specific version of ndn-cxx?

**Comment by Pesa** [comment]
Yes. If you're compiling NLSR from git master branch, you'll also need the master branch of ndn-cxx (and PSync). Older releases have different requirements.
