### ISSUE TITLE
./waf issue

### ISSUE THREAD

**Issue by lalalaporo** [named-data/NLSR#17]
> Setting top to                           : /home/hacks/.src/NLSR
> Setting out to                           : /home/hacks/.src/NLSR/build
> Checking for 'g++' (C++ compiler)        : /usr/bin/g++
> Checking C++ compiler version            : 9.4.0
> Checking supported CXXFLAGS              : -std=c++17
> Checking supported LINKFLAGS             : -fuse-ld=gold
> Checking for program 'doxygen'           : /usr/bin/doxygen
> Checking for program 'tar'               : /usr/bin/tar
> Checking for program 'sphinx-build'      : /home/hacks/.local/bin/sphinx-build
> Checking for program 'dot'               : /usr/bin/dot
> Checking for program 'pkgconf, pkg-config' : /usr/bin/pkg-config
> Checking for 'libndn-cxx'                  : yes
> Checking for program 'dpkg-architecture'   : /usr/bin/dpkg-architecture
> Checking boost includes                    : 1.71.0
> Checking boost libs                        : boost_system boost_iostreams boost_filesystem boost_regex
> Checking for boost linkage                 : ok
> Checking for 'PSync'                       : yes
> Checking supported CXXFLAGS                : -O2 -g -pedantic -Wall -Wextra -Wcatch-value=2 -Wextra-semi -Wnon-virtual-dtor -Wno-unused-parameter -fdiagnostics-color
> Checking supported LINKFLAGS               : -Wl,-O1
> 'configure' finished successfully (1.302s)
> hacks@ECIT01681:~/.src/NLSR$ ./waf
> Waf: Entering directory `/home/hacks/.src/NLSR/build'
> [ 8/40] Compiling src/adjacent.cpp
> [ 9/40] Compiling src/name-prefix-list.cpp
> [10/40] Compiling src/update/nfd-rib-command-processor.cpp
> [11/40] Compiling src/update/prefix-update-commands.cpp
> [12/40] Compiling src/update/nfd-rib-commands.cpp
> [13/40] Compiling src/route/fib.cpp
> [14/40] Compiling src/lsdb.cpp
> [21/40] Compiling src/lsa/coordinate-lsa.cpp
> [36/40] Compiling src/nlsr.cpp
> [37/40] Compiling src/main.cpp
> [38/40] Compiling tools/nlsrc.cpp
> ../src/lsdb.cpp: In member function ‘bool nlsr::Lsdb::processInterestForLsa(const ndn::Interest&, const ndn::Name&, nlsr::Lsa::Type, uint64_t)’:
> ../src/lsdb.cpp:209:80: error: no matching function for call to ‘psync::SegmentPublisher::publish(const ndn::Name&, const ndn::Name&, const ndn::Block&, ndn::time::seconds&, const ndn::security::SigningInfo&)’
>   209 |                                  m_lsaRefreshTime, m_confParam.getSigningInfo());
>       |                                                                                ^
> In file included from /usr/local/include/PSync/producer-base.hpp:26,
>                  from /usr/local/include/PSync/full-producer.hpp:23,
>                  from ../src/communication/sync-protocol-adapter.hpp:33,
>                  from ../src/communication/sync-logic-handler.hpp:28,
>                  from ../src/lsdb.hpp:32,
>                  from ../src/lsdb.cpp:22:
> /usr/local/include/PSync/segment-publisher.hpp:51:3: note: candidate: ‘void psync::SegmentPublisher::publish(const ndn::Name&, const ndn::Name&, nonstd::span_lite::span<const unsigned char>, ndn::time::milliseconds)’   51 |   publish(const ndn::Name& interestName, const ndn::Name& dataName,
>       |   ^~~~~~~
> /usr/local/include/PSync/segment-publisher.hpp:51:3: note:   candidate expects 4 arguments, 5 provided

Fail ./waf, It seem like PSync was updated a few days ago and break this.

https://github.com/named-data/PSync/commit/b68f28497e29a5cfcbb5ae2de33956f34e814760?diff=split

**Comment by lalalaporo** [comment]
https://github.com/Pesa/NLSR

This solves the problem!!

**Comment by Pesa** [comment]
Fixed in 65ee9921497b5b7317e19abeebc80e297765032a
