### ISSUE TITLE
Linker error with ChronoSync when building.

### ISSUE THREAD

**Issue by travLappy** [named-data/NLSR#8]
Upon the "sudo ./waf" command, I receive several undefined reference errors with ChronoSync:

> VirtualBox:~/NLSR$ sudo ./waf 
Waf: Entering directory `/home/travis/NLSR/build'
[47/49] Linking build/bin/nlsr
[49/49] Linking build/bin/nlsrc
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::util::Sha256::Sha256()'
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::util::Sha256::computeDigest()'
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::util::Sha256::reset()'
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::util::Sha256::operator<<(ndn::Block const&)'
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::util::Sha256::operator<<(unsigned long)'
/usr/local/lib/libChronoSync.so: error: undefined reference to 'ndn::InMemoryStorage::erase(ndn::Name const&, bool)'

I have successfully installed both ndn-cxx and ChronoSync onto my system.

**Comment by gorgonical** [comment]
Travis,

This could be a few things:

* If you re-built a newer version of ChronoSync, you need to make sure
you deleted all the old includes, and then re-configure and re-build
NLSR. It's also a good idea to delete the libs: /usr/local/lib
and /usr/local/ChronoSync.

* You may have forgotten to do an `sudo ldconfig` after installing or
updating ChronoSync.

* You may have updated ChronoSync without updating NLSR, too. They tend
to keep pace with each other, so if you're not using release commits
you need to be careful of your code versions.

-- 
-Nick

**Comment by travLappy** [comment]
I did the `sudo ldconfig` after installing ChronoSync. I also installed ChronoSync and NLSR for the first time that day, so I think the versions are both up to date. So when you say delete the libs, do you mean deleting the `.so` files related to ChronoSync?

**Comment by gorgonical** [comment]
Travis,

If you had only just installed NLSR and ChronoSync that day, it looks
like you may have an older version of ndn-cxx. Recently, maybe around a
month or two ago, some things got moved around in the source tree, so
old includes and libraries are invalid. You should try:

sudo rm rf /usr/local/lib/libndn-cxx.*
sudo rm rf /usr/local/include/ndn-cxx
sudo rm rf /usr/local/lib/ChronoSync
sudo rm rf /usr/local/include/libChronoSync.*

And try to re-build ndn-cxx, then ChronoSync, then NLSR.

-- 
-Nick

**Comment by travLappy** [comment]
It looks like re-building ndn-cxx along with ChronoSync did the trick. Thank you.
