### ISSUE TITLE
NLSR simulation

### ISSUE THREAD

**Issue by ningjing-m** [named-data/NLSR#9]
How can I simulate NLSR with ndnSIM installed?

**Comment by sofiya07** [comment]
Any lastest code available for ndn-NLSR, if yes the link and the installation steps please.

**Comment by agawande** [comment]
Sorry, no latest code is available to simulate NLSR in ndnSIM. Help can be provided on NLSR or ndnSIM mailing list if you wish to bring the port up to date (https://named-data.net/codebase/platform/support/mailing-lists/).

**Comment by sofiya07** [comment]
Thanks for the response Ashlesh

Any link to a working code, I need it for one of my projects.
